// <auto-generated />
using AspMvcAssignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspMvcAssignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221121105450_Seeded some Person data")]
    partial class SeededsomePersondata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspMvcAssignment.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBooks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "1a00b3c0-b630-4a13-acb9-41d45ec943df",
                            City = "Devon",
                            Name = "Agatha Christie",
                            NumberOfBooks = 85
                        },
                        new
                        {
                            Id = "8d32397a-9c9e-4bf5-a4df-8f5234d46e70",
                            City = "New Hampshire",
                            Name = "Dan Brown",
                            NumberOfBooks = 7
                        },
                        new
                        {
                            Id = "93e2a945-a082-48e8-9d2d-996e03da8962",
                            City = "Tokyo",
                            Name = "Yasuo Uchida",
                            NumberOfBooks = 130
                        },
                        new
                        {
                            Id = "45d7888d-621b-4c0d-ba00-a7bf2593f805",
                            City = "Tanta",
                            Name = "Ahmed Tawfik",
                            NumberOfBooks = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
