// <auto-generated />
using AspMvcAssignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspMvcAssignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221124094313_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspMvcAssignment.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBooks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Devon",
                            Name = "Agatha Christie",
                            NumberOfBooks = 85
                        },
                        new
                        {
                            Id = 2,
                            City = "New Hampshire",
                            Name = "Dan Brown",
                            NumberOfBooks = 7
                        },
                        new
                        {
                            Id = 3,
                            City = "Tokyo",
                            Name = "Yasuo Uchida",
                            NumberOfBooks = 130
                        },
                        new
                        {
                            Id = 4,
                            City = "Tanta",
                            Name = "Ahmed Tawfik",
                            NumberOfBooks = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
